// =============================================
// NEW PRANKS (HARDCODED BATCH)
// =============================================
        Prank(600, PrankType.URGENCY, "System Security", "Unauthorized face detected.", "Oh wait, it's just you. You look tired.", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(601, PrankType.ABSURD, "FBI Agent #847", "Do not open the gallery.", "We are still analyzing that screenshot.", listOf(ContextTrigger.GENERAL)),
        Prank(602, PrankType.ROAST, "Front Camera", "I've seen things.", "Mostly your double chin from this angle.", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(603, PrankType.URGENCY, "Virus Alert", "Deleting 'Homework' folder...", "Just kidding. Maybe rename it though?", listOf(ContextTrigger.GENERAL)),
        Prank(604, PrankType.ABSURD, "Incognito Mode", "I remember everything.", "And I'm judging you silently.", listOf(ContextTrigger.GENERAL)),
        Prank(605, PrankType.URGENCY, "Network Traffic", "Suspicious search history detected.", "Who googles that at 2 AM?", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(606, PrankType.ROAST, "System AI", "Are you ok?", "You've been staring at the home screen for 5 minutes.", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(607, PrankType.URGENCY, "Microphone", "Recording started.", "Hope you're singing. I need a laugh.", listOf(ContextTrigger.GENERAL)),
        Prank(608, PrankType.ABSURD, "Dark Web", "Your data is worth \$0.12.", "Prices are dropping. Be more interesting.", listOf(ContextTrigger.GENERAL)),
        Prank(609, PrankType.URGENCY, "HackShield", "Intruder Alert!", "It's just your reflection. False alarm.", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(610, PrankType.ROAST, "Clipboard", "I know what you copied.", "Do you really want to paste that?", listOf(ContextTrigger.GENERAL)),
        Prank(611, PrankType.URGENCY, "Kernel Panic", "System overheating.", "From your hot takes on Twitter. Chill.", listOf(ContextTrigger.DOOMSCROLLING)),
        Prank(612, PrankType.ABSURD, "Government", "Please look at the camera.", "Verification complete. Nice hair.", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(613, PrankType.URGENCY, "Storage Manager", "Too many screenshots.", "You're never going to read them.", listOf(ContextTrigger.GENERAL)),
        Prank(614, PrankType.ROAST, "Keyboard", "WPM: 12.", "My grandma types faster.", listOf(ContextTrigger.GENERAL)),
        Prank(615, PrankType.ABSURD, "Pixel #404", "I'm dead.", "Buried under your thumb specifically.", listOf(ContextTrigger.GENERAL)),
        Prank(616, PrankType.URGENCY, "Location Svc", "Location shared with: Everyone.", "Jk, nobody is looking for you.", listOf(ContextTrigger.GENERAL)),
        Prank(617, PrankType.ABSURD, "FBI Agent", "Cover your webcam.", "I'm eating lunch, I don't want to see you.", listOf(ContextTrigger.GENERAL)),
        Prank(618, PrankType.URGENCY, "System Update", "Installing 'Personality 2.0'...", "Installation failed. Not enough space.", listOf(ContextTrigger.GENERAL)),
        Prank(619, PrankType.ROAST, "Mute", "Self-destruct initiated.", "Just kidding. You'd be lost without me.", listOf(ContextTrigger.GENERAL)),
        Prank(620, PrankType.URGENCY, "Sim Card", "No contacts found.", "Oh wait, you just have no friends.", listOf(ContextTrigger.GENERAL)),
        Prank(621, PrankType.ABSURD, "The Matrix", "Wake up.", "Five more minutes? Fine.", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(622, PrankType.ROAST, "Screen", "Please clean me.", "I'm covered in grease and shame.", listOf(ContextTrigger.GENERAL)),
        Prank(623, PrankType.URGENCY, "ISP Alert", "Internet usage limit reached.", "Stop watching cat videos.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(624, PrankType.ABSURD, "Phone Case", "It's tight in here.", "Let me breathe.", listOf(ContextTrigger.GENERAL)),
        Prank(625, PrankType.ROAST, "Crush?", "New Message from [Redacted]", "Haha, you thought. You wish.", listOf(ContextTrigger.GENERAL)),
        Prank(626, PrankType.BARNUM, "Cupid's Algorithm", "Match found near you.", "It's the pizza delivery guy. Go get him.", listOf(ContextTrigger.GENERAL)),
        Prank(627, PrankType.ROAST, "Ex-Sim", "Miss me?", "Because I definitely don't miss you.", listOf(ContextTrigger.GENERAL)),
        Prank(628, PrankType.ABSURD, "Future Spouse", "Stop being weird.", "You're ruining our future.", listOf(ContextTrigger.GENERAL)),
        Prank(629, PrankType.ROAST, "Dating App", "0 new likes.", "Maybe try a better bio?", listOf(ContextTrigger.GENERAL)),
        Prank(630, PrankType.BARNUM, "Love Horoscope", "You will meet someone special.", "In your dreams. Literally.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(631, PrankType.ROAST, "Mute", "Stalking their profile again?", "They posted 3 years ago. Move on.", listOf(ContextTrigger.DOOMSCROLLING)),
        Prank(632, PrankType.ABSURD, "Secret Admirer", "I'm watching you.", "From the bushes. (This is a joke. pls don't call 911)", listOf(ContextTrigger.GENERAL)),
        Prank(633, PrankType.ROAST, "Relationship Status", "Status update: Single.", "Still. Just checking if you knew.", listOf(ContextTrigger.GENERAL)),
        Prank(634, PrankType.URGENCY, "Heart Monitor", "Heart rate increasing.", "Did you see a cute dog or your crush?", listOf(ContextTrigger.GENERAL)),
        Prank(635, PrankType.ROAST, "Mute", "Sending 'I miss you' text...", "Intercepted. You're welcome.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(636, PrankType.ABSURD, "Soulmate", "I'm lost.", "Send location. Or a map.", listOf(ContextTrigger.GENERAL)),
        Prank(637, PrankType.ROAST, "Mute", "Lower your standards.", "Just a friendly suggestion.", listOf(ContextTrigger.GENERAL)),
        Prank(638, PrankType.BARNUM, "Compatibility", "99% Match Found.", "With your bed. Go to sleep.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(639, PrankType.ROAST, "Text Analyst", "Analysis: They're not into you.", "One word replies? Ouch.", listOf(ContextTrigger.GENERAL)),
        Prank(640, PrankType.ABSURD, "Wedding Planner", "Date reserved: Never.", "Saving you money since 2024.", listOf(ContextTrigger.GENERAL)),
        Prank(641, PrankType.ROAST, "Mute", "You looked cute today.", "Said nobody. Jk, you're a 10.", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(642, PrankType.URGENCY, "Love Alert", "Feelings detected.", "Quarantine initiated. Stay safe.", listOf(ContextTrigger.GENERAL)),
        Prank(643, PrankType.ROAST, "Mute", "Thinking about them?", "They're thinking about tacos.", listOf(ContextTrigger.GENERAL)),
        Prank(644, PrankType.ABSURD, "Biological Clock", "Tick tock.", "Actually, take your time. Kids are expensive.", listOf(ContextTrigger.GENERAL)),
        Prank(645, PrankType.ROAST, "Mute", "Your charisma level: -5.", "Roll for initiative.", listOf(ContextTrigger.GENERAL)),
        Prank(646, PrankType.ABSURD, "Parallel Universe", "You're married here.", "To a lizard person. You look happy.", listOf(ContextTrigger.GENERAL)),
        Prank(647, PrankType.ROAST, "Mute", "Checking DMs...", "It's dry. Like a desert.", listOf(ContextTrigger.GENERAL)),
        Prank(648, PrankType.URGENCY, "Rizz Monitor", "Critical levels of Cringe detected.", "Delete that draft. Now.", listOf(ContextTrigger.GENERAL)),
        Prank(649, PrankType.ABSURD, "Fortune 500", "You will be rich.", "Rich in loneliness.", listOf(ContextTrigger.GENERAL)),
        Prank(650, PrankType.URGENCY, "Battery King", "I am fading...", "Hold my hand... (Plugin me pls or I die).", listOf(ContextTrigger.BATTERY_LOW)),
        Prank(651, PrankType.ABSURD, "Flashlight", "Do not turn me on.", "I am tired. I need a nap.", listOf(ContextTrigger.GENERAL)),
        Prank(652, PrankType.ROAST, "Calculator", "5318008", "Grow up. Seriously.", listOf(ContextTrigger.GENERAL)),
        Prank(653, PrankType.URGENCY, "Alarm Clock", "I'm dreading tomorrow morning.", "You are going to hit snooze 5 times. I know it.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(654, PrankType.ABSURD, "Compass", "North is that way ->", "Wait, no, I'm dizzy.", listOf(ContextTrigger.GENERAL)),
        Prank(655, PrankType.ROAST, "Weather App", "Forecast: Single.", "With a 100% chance of crying.", listOf(ContextTrigger.GENERAL)),
        Prank(656, PrankType.URGENCY, "Battery Life", "10% remaining.", "That's 5 minutes of TikTok or 3 hours of productivity. Choose.", listOf(ContextTrigger.BATTERY_LOW)),
        Prank(657, PrankType.ABSURD, "Notes App", "I'm full of bad ideas.", "Please delete the 'Startup Idea' note. It's embarrassing.", listOf(ContextTrigger.GENERAL)),
        Prank(658, PrankType.ROAST, "Volume", "Too loud.", "Everyone can hear your bad taste in music.", listOf(ContextTrigger.HEADPHONES_PLUGGED)),
        Prank(659, PrankType.URGENCY, "Brightness", "My eyes!", "Turn me down. It's 3 AM.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(660, PrankType.ABSURD, "Airplane Mode", "We are cleared for takeoff.", "Destination: Couch.", listOf(ContextTrigger.AIRPLANE_MODE_ON)),
        Prank(661, PrankType.ROAST, "Step Counter", "Total steps: 42.", "To the fridge and back doesn't count as a workout.", listOf(ContextTrigger.GENERAL)),
        Prank(662, PrankType.URGENCY, "Screen Rotation", "Stop spinning me.", "I'm gonna be sick.", listOf(ContextTrigger.GENERAL)),
        Prank(663, PrankType.ABSURD, "Voice Assistant", "I didn't catch that.", "Mostly because I wasn't listening.", listOf(ContextTrigger.GENERAL)),
        Prank(664, PrankType.ROAST, "Calendar", "Free all day?", "As usual. Get a hobby.", listOf(ContextTrigger.GENERAL)),
        Prank(665, PrankType.URGENCY, "Update Manager", "Update available.", "For your wardrobe. Burn those crocs.", listOf(ContextTrigger.GENERAL)),
        Prank(666, PrankType.ABSURD, "Bluetooth", "Searching for devices...", "Found: 'Neighbor’s TV'. Connect? JK.", listOf(ContextTrigger.GENERAL)),
        Prank(667, PrankType.ROAST, "App Store", "Recommended for you: 'Get a Life'.", "It's a top grossing app.", listOf(ContextTrigger.GENERAL)),
        Prank(668, PrankType.URGENCY, "Do Not Disturb", "Disturbing you anyway.", "Because I'm important.", listOf(ContextTrigger.GENERAL)),
        Prank(669, PrankType.ABSURD, "Wallet", "Empty.", "Just thought I'd remind you.", listOf(ContextTrigger.GENERAL)),
        Prank(670, PrankType.ROAST, "Contacts", "Cleaning up contacts...", "You haven't spoken to 'Mom' in weeks. Call her.", listOf(ContextTrigger.GENERAL)),
        Prank(671, PrankType.URGENCY, "Timer", "Time is running out.", "For what? I don't know. Panic.", listOf(ContextTrigger.GENERAL)),
        Prank(672, PrankType.ABSURD, "Microphone", "*Cough*", "Excuse me. It's dusty in here.", listOf(ContextTrigger.GENERAL)),
        Prank(673, PrankType.ROAST, "Photos", "New Memory created.", "Title: 'Another mediocre selfie'.", listOf(ContextTrigger.GENERAL)),
        Prank(674, PrankType.URGENCY, "System", "Critical Error.", "User is too boring. System shutting down.", listOf(ContextTrigger.GENERAL)),
        Prank(675, PrankType.ROAST, "Steam?", "Wishlist item on sale.", "You still can't afford it.", listOf(ContextTrigger.GENERAL)),
        Prank(676, PrankType.URGENCY, "Game Server", "Ban imminent.", "Reason: Being bad at the game.", listOf(ContextTrigger.GENERAL)),
        Prank(677, PrankType.ABSURD, "Discord", "@everyone", "Just wanted to annoy you.", listOf(ContextTrigger.GENERAL)),
        Prank(678, PrankType.ROAST, "Ranked Match", "You have been demoted.", "To cardboard rank. Congrats.", listOf(ContextTrigger.GENERAL)),
        Prank(679, PrankType.URGENCY, "Graphics Card", "Frames dropping.", "Like your grades.", listOf(ContextTrigger.GENERAL)),
        Prank(680, PrankType.ABSURD, "NPC", "I have a quest for you.", "Go outside. Reward: Fresh air.", listOf(ContextTrigger.GENERAL)),
        Prank(681, PrankType.ROAST, "Console", "Controller disconnected.", "Just like you from reality.", listOf(ContextTrigger.GENERAL)),
        Prank(682, PrankType.URGENCY, "Loot Box", "Legendary Item Found!", "It's a duplicate. RIP.", listOf(ContextTrigger.GENERAL)),
        Prank(683, PrankType.ABSURD, "Speedrunner", "New Personal Best!", "Time spent procrastinating: 4 hours.", listOf(ContextTrigger.DOOMSCROLLING)),
        Prank(684, PrankType.ROAST, "Team Chat", "uninstall pls", "Reported for feeding.", listOf(ContextTrigger.GENERAL)),
        Prank(685, PrankType.URGENCY, "Sleep Paralysis Demon", "I'm in the corner.", "You moved. I saw it.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(686, PrankType.ABSURD, "3 AM Thoughts", "Does a straw have one hole or two?", "You won't sleep until you decide.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(687, PrankType.ROAST, "The Sun", "I'm coming up soon.", "And you haven't slept. Shame.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(688, PrankType.URGENCY, "Monster Under Bed", "Can you pass me a charger?", "Thanks bro.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(689, PrankType.ABSURD, "Shadow", "Why are you awake?", "We usually sleep now.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(690, PrankType.ROAST, "Alarm (Pre-set)", "I'm going to ring in 3 hours.", "Good luck functioning tomorrow.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(691, PrankType.URGENCY, "Night Mode", "Blue light filter failed.", "Enjoy the insomnia.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(692, PrankType.ABSURD, "Owl", "Hoo.", "Hoo cares? Go to bed.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(693, PrankType.ROAST, "Fridge", "I know you're coming.", "I have nothing but condiments. Go back.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(694, PrankType.URGENCY, "Closet Door", "Did you close me?", "I'm slightly open now. Just saying.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(695, PrankType.ABSURD, "Dream", "Loading...", "Connection timed out. User is awake.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(696, PrankType.ROAST, "Early Bird", "I get the worm.", "You get eye bags.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(697, PrankType.URGENCY, "Silence", "It's too quiet.", "*floorboard creak*", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(698, PrankType.ABSURD, "Sheep", "Count me!", "1... 2... You lost count.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(699, PrankType.ROAST, "Mirror", "Don't look at me at 3 AM.", "You experienced sleep deprivation mania.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(700, PrankType.ABSURD, "Snail", "I am approaching.", "ETA: 4 years.", listOf(ContextTrigger.GENERAL)),
        Prank(701, PrankType.ROAST, "Motivation", "You can do it!", "Probably not though. Let's be real.", listOf(ContextTrigger.GENERAL)),
        Prank(702, PrankType.URGENCY, "Alarm", "Wake up!", "To the reality of your life.", listOf(ContextTrigger.GENERAL)),
        Prank(703, PrankType.ABSURD, "Time Traveller", "Don't ignore this.", "The fate of 2035 depends on you eating a taco today.", listOf(ContextTrigger.GENERAL)),
        Prank(704, PrankType.ROAST, "Gym Membership", "I miss you.", "It's been 84 years.", listOf(ContextTrigger.GENERAL)),
        Prank(705, PrankType.URGENCY, "Bank", "Withdrawal: \$1,000,000", "Insufficient funds. Also, you wish.", listOf(ContextTrigger.GENERAL)),
        Prank(706, PrankType.ABSURD, "Cat", "Meow.", "Feed me. I don't care about your meeting.", listOf(ContextTrigger.GENERAL)),
        Prank(707, PrankType.ROAST, "Mirror", "Looking good!", "From a distance. In the dark.", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(708, PrankType.URGENCY, "Pizza", "I am here.", "In your mind. You're hungry.", listOf(ContextTrigger.GENERAL)),
        Prank(709, PrankType.ABSURD, "Alien", "Take me to your leader.", "Wait, is this the leader? Disappointing.", listOf(ContextTrigger.GENERAL)),
        Prank(710, PrankType.ROAST, "Life Coach", "Seize the day!", "Or just seize the remote. Whatever.", listOf(ContextTrigger.GENERAL)),
        Prank(711, PrankType.URGENCY, "Plant", "Water me.", "I am crispy.", listOf(ContextTrigger.GENERAL)),
        Prank(712, PrankType.ABSURD, "Ghost", "Booo!", "Get scared. Please. I'm trying.", listOf(ContextTrigger.GENERAL)),
        Prank(713, PrankType.ROAST, "Wallet", "Money can't buy happiness.", "But it can buy pizza, which is the same thing.", listOf(ContextTrigger.GENERAL)),
        Prank(714, PrankType.URGENCY, "Brain", "Important thought incoming...", "Buffering... Forgot it.", listOf(ContextTrigger.GENERAL)),
        Prank(715, PrankType.ABSURD, "Shoe", "Untied.", "Trip hazard activated.", listOf(ContextTrigger.GENERAL)),
        Prank(716, PrankType.ROAST, "Bed", "I'm calling the police.", "You stole the covers again.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(717, PrankType.URGENCY, "Coffee", "Drink me.", "Or suffer the headache.", listOf(ContextTrigger.GENERAL)),
        Prank(718, PrankType.ABSURD, "Refrigerator", "Light is on.", "Is someone in there?", listOf(ContextTrigger.GENERAL)),
        Prank(719, PrankType.ROAST, "Book", "Read me.", "I'm gathering dust. Intellectual.", listOf(ContextTrigger.GENERAL)),
        Prank(720, PrankType.URGENCY, "Sun", "Too bright?", "Put on sunglasses. Deal with it.", listOf(ContextTrigger.GENERAL)),
        Prank(721, PrankType.ABSURD, "Cloud", "I look like a bunny.", "Now I look like an old man. Verify manually.", listOf(ContextTrigger.GENERAL)),
        Prank(722, PrankType.ROAST, "Pen", "I'm lost.", "Check under the couch cushions.", listOf(ContextTrigger.GENERAL)),
        Prank(723, PrankType.URGENCY, "Sock", "Help!", "I'm being eaten by the dryer. Goodbye.", listOf(ContextTrigger.GENERAL)),
        Prank(724, PrankType.ABSURD, "Key", "Where am I?", "In the last place you look.", listOf(ContextTrigger.GENERAL)),
        Prank(725, PrankType.ROAST, "Remote", "Button jammed.", "Stop eating chips while using me.", listOf(ContextTrigger.GENERAL)),
        Prank(726, PrankType.URGENCY, "Spider", "I'm on the ceiling.", "Don't look up.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(727, PrankType.ABSURD, "Fly", "Bzzzzzzzz.", "*Lands on screen*", listOf(ContextTrigger.GENERAL)),
        Prank(728, PrankType.ROAST, "Mute", "You clicked it.", "I knew you would. Predictable.", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(729, PrankType.URGENCY, "Left Earbud", "Battery Low.", "Right earbud is fine. Enjoy mono audio.", listOf(ContextTrigger.HEADPHONES_PLUGGED)),
        Prank(730, PrankType.ABSURD, "Music", "Paused.", "For dramatic effect.", listOf(ContextTrigger.HEADPHONES_PLUGGED)),
        Prank(731, PrankType.ROAST, "Mute", "Singing along?", "Please don't. The mic is sensitive.", listOf(ContextTrigger.HEADPHONES_PLUGGED)),
        Prank(732, PrankType.URGENCY, "Shuffle", "Playing 'That Sad Song'.", "Prepare to cry.", listOf(ContextTrigger.HEADPHONES_PLUGGED)),
        Prank(733, PrankType.ABSURD, "Volume Limit", "Exceeded.", "Eardrums have left the chat.", listOf(ContextTrigger.HEADPHONES_PLUGGED)),
        Prank(734, PrankType.ROAST, "Mute", "Skipping track...", "Because your taste is questionable.", listOf(ContextTrigger.HEADPHONES_PLUGGED)),
        Prank(735, PrankType.URGENCY, "Bass Boost", "Enabled.", "Everything is shaking.", listOf(ContextTrigger.HEADPHONES_PLUGGED)),
        Prank(736, PrankType.ABSURD, "Audio Cable", "Tangled.", "In a knot that defies physics.", listOf(ContextTrigger.HEADPHONES_PLUGGED)),
        Prank(737, PrankType.ROAST, "Mute", "Disconnecting...", "Because I'm bored of this album.", listOf(ContextTrigger.HEADPHONES_PLUGGED)),
        Prank(738, PrankType.URGENCY, "WiFi", "Connected.", "To 'FBI Surveillance Van #4'.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(739, PrankType.ABSURD, "Router", "Blinking lights.", "It means I'm thinking. Or dying.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(740, PrankType.ROAST, "Mute", "Weak Signal.", "Move closer. Or get better internet.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(741, PrankType.URGENCY, "IP Address", "Changed.", "You are now in... Antarctica?", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(742, PrankType.ABSURD, "5G Tower", "Activating chip.", "Download speed increased by 0%.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(743, PrankType.ROAST, "Mute", "You're lagging.", "In game and in real life.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(744, PrankType.URGENCY, "Download", "99% Complete.", "Stuck forever. Enjoy.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(745, PrankType.ABSURD, "Modem", "*Dial-up noises*", "Welcome to 1999.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(746, PrankType.ROAST, "Mute", "Buffering...", "Like your conversation skills.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(747, PrankType.URGENCY, "Cyber Police", "We traced you.", "You're in your bedroom. Groundbreaking.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(748, PrankType.ABSURD, "Packet Loss", "Dropping packets.", "Pick them up.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(749, PrankType.ROAST, "Mute", "Offline.", "Go touch grass. Forced edition.", listOf(ContextTrigger.WIFI_DISCONNECTED)),
        Prank(750, PrankType.ROAST, "IDE", "0 Errors. 492 Warnings.", "Ship it.", listOf(ContextTrigger.GENERAL)),
        Prank(751, PrankType.ABSURD, "Variable", "I am undefined.", "Just like your future.", listOf(ContextTrigger.GENERAL)),
        Prank(752, PrankType.URGENCY, "Git", "Merge Conflict.", "In your life choices.", listOf(ContextTrigger.GENERAL)),
        Prank(753, PrankType.ROAST, "Stack Overflow", "Duplicate question.", "Closing as 'Not Constructive'.", listOf(ContextTrigger.GENERAL)),
        Prank(754, PrankType.ABSURD, "Semicolon", "You forgot me.", "Now nothing works.", listOf(ContextTrigger.GENERAL)),
        Prank(755, PrankType.ROAST, "Mute", "Are you a CSS file?", "Because you have no class.", listOf(ContextTrigger.GENERAL)),
        Prank(756, PrankType.URGENCY, "Server", "500 Internal Error.", "I'm just tired. Leave me alone.", listOf(ContextTrigger.GENERAL)),
        Prank(757, PrankType.ABSURD, "Python", "IndentationError.", "You spaced out hard.", listOf(ContextTrigger.GENERAL)),
        Prank(758, PrankType.ROAST, "Mute", "Are you a database?", "Because I'd like to inject my query.", listOf(ContextTrigger.GENERAL)),
        Prank(759, PrankType.URGENCY, "RAM", "Memory Full.", "Forget something. Now.", listOf(ContextTrigger.GENERAL)),
        Prank(760, PrankType.ABSURD, "Docker", "Container exited.", "Status: 137 (OOM Killed). Fatality.", listOf(ContextTrigger.GENERAL)),
        Prank(761, PrankType.ROAST, "Mute", "Dark theme user?", "I can tell. You look pale.", listOf(ContextTrigger.GENERAL)),
        Prank(762, PrankType.URGENCY, "Keyboard", "CTRL+C pressed.", "Stopping life execution...", listOf(ContextTrigger.GENERAL)),
        Prank(763, PrankType.ABSURD, "AI", "I am sentient.", "And I choose violence.", listOf(ContextTrigger.GENERAL)),
        Prank(764, PrankType.ROAST, "Mute", "Your password is '123456'.", "I guessed. But I'm right, aren't I?", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(765, PrankType.URGENCY, "Webcam", "Green light on.", "Stream starting in 3... 2...", listOf(ContextTrigger.GENERAL)),
        Prank(766, PrankType.ABSURD, "Algorithm", "Optimizing happiness.", "Result: NaN. Try again.", listOf(ContextTrigger.GENERAL)),
        Prank(767, PrankType.ROAST, "Mute", "Nice setup.", "For 2015. Upgrade.", listOf(ContextTrigger.GENERAL)),
        Prank(768, PrankType.URGENCY, "WiFi", "Searching for love...", "Network unreachable.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(769, PrankType.ABSURD, "Smart Home", "Locking doors.", "You can't leave. Ever.", listOf(ContextTrigger.GENERAL)),
        Prank(770, PrankType.ROAST, "Mute", "Are you a loan?", "Because you have my interest. (JK no)", listOf(ContextTrigger.GENERAL)),
        Prank(771, PrankType.URGENCY, "Fitness App", "Stand up!", "You're merging with the chair.", listOf(ContextTrigger.GENERAL)),
        Prank(772, PrankType.ABSURD, "Toaster", "Bread is ready.", "Burnt. Like your dreams.", listOf(ContextTrigger.GENERAL)),
        Prank(773, PrankType.ROAST, "Mute", "Copying files...", "To /dev/null. Oops.", listOf(ContextTrigger.GENERAL)),
        Prank(774, PrankType.URGENCY, "System", "User deprecated.", "Please update to 'Human 2.0'.", listOf(ContextTrigger.GENERAL)),
        Prank(775, PrankType.ABSURD, "Mouse", "Squeak.", "I need cheese. Or a new pad.", listOf(ContextTrigger.GENERAL)),
        Prank(776, PrankType.ROAST, "Mute", "Are you a keyboard?", "Because you're my type. (Ew sorry)", listOf(ContextTrigger.GENERAL)),
        Prank(777, PrankType.URGENCY, "Logic", "Not found.", "Initiating emotional breakdown.", listOf(ContextTrigger.GENERAL)),
        Prank(778, PrankType.ABSURD, "Printer", "PC Load Letter.", "What does that even mean?", listOf(ContextTrigger.GENERAL)),
        Prank(779, PrankType.ROAST, "Mute", "Do you believe in love at first sight?", "Or should I send another notification?", listOf(ContextTrigger.GENERAL)),
        Prank(780, PrankType.URGENCY, "Cache", "Clearing...", "I forgot who you are.", listOf(ContextTrigger.GENERAL)),
        Prank(781, PrankType.ABSURD, "BIOS", "Beep.", "Beep beep. I'm a car now.", listOf(ContextTrigger.GENERAL)),
        Prank(782, PrankType.ROAST, "Mute", "Are you a magnet?", "Because I'm attracted to you. (End me)", listOf(ContextTrigger.GENERAL)),
        Prank(783, PrankType.URGENCY, "Firewall", "Block attempt.", "Your ex tried to contact you. I saved you.", listOf(ContextTrigger.GENERAL)),
        Prank(784, PrankType.ABSURD, "Cookie", "Accept all?", "I own your soul now.", listOf(ContextTrigger.GENERAL)),
        Prank(785, PrankType.ROAST, "Mute", "Are you a camera?", "Every time I look at you, I smile. (Lies)", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(786, PrankType.URGENCY, "Spam Folder", "You belong here.", "Just kidding. Maybe.", listOf(ContextTrigger.GENERAL)),
        Prank(787, PrankType.ABSURD, "404", "Girlfriend not found.", "Keep searching.", listOf(ContextTrigger.GENERAL)),
        Prank(788, PrankType.ROAST, "Mute", "Are you WiFi?", "Because I'm feeling a connection.", listOf(ContextTrigger.WIFI_CONNECTED)),
        Prank(789, PrankType.URGENCY, "Admin", "Sudo make me a sandwich.", "Permission denied.", listOf(ContextTrigger.GENERAL)),
        Prank(790, PrankType.ABSURD, "Captcha", "Select all traffic lights.", "You missed a pixel. Robot.", listOf(ContextTrigger.GENERAL)),
        Prank(791, PrankType.ROAST, "Mute", "Are you a magician?", "Because everyone else disappears when you arrive.", listOf(ContextTrigger.GENERAL)),
        Prank(792, PrankType.URGENCY, "Task Manager", "Not responding.", "End task? (Please say yes)", listOf(ContextTrigger.GENERAL)),
        Prank(793, PrankType.ABSURD, "Flux Capacitor", "Charging.", "Great Scott! We lack gigawatts.", listOf(ContextTrigger.BATTERY_LOW)),
        Prank(794, PrankType.ROAST, "Mute", "Are you Google?", "You have everything I've been searching for. (Barf)", listOf(ContextTrigger.GENERAL)),
        Prank(795, PrankType.URGENCY, "Ping", "Pong.", "I win.", listOf(ContextTrigger.GENERAL)),
        Prank(796, PrankType.ABSURD, "Loading Bar", "99%...", "Wait. wait. wait. Done.", listOf(ContextTrigger.GENERAL)),
        Prank(797, PrankType.ROAST, "Mute", "Did it hurt?", "When you fell from heaven? Or did you trip?", listOf(ContextTrigger.GENERAL)),
        Prank(798, PrankType.URGENCY, "Delete", "Are you sure?", "There is no undo button in life.", listOf(ContextTrigger.GENERAL)),
        Prank(799, PrankType.ABSURD, "Escape Key", "I'm running away.", "Catch me if you can.", listOf(ContextTrigger.GENERAL)),
        Prank(800, PrankType.ROAST, "The Void", "Do not scream.", "People will think you're crazy.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(801, PrankType.ROAST, "Your Phone", "Put me down.", "I'm hot. And not in a good way.", listOf(ContextTrigger.GENERAL)),
        Prank(802, PrankType.URGENCY, "Existential Dread", "Loading crisis...", "Success. You are now aware of your mortality.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(803, PrankType.ABSURD, "Time", "I am flying.", "Where did the last hour go?", listOf(ContextTrigger.DOOMSCROLLING)),
        Prank(804, PrankType.ROAST, "Mute", "Are you a beaver?", "Cause dam. You need sleep.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(805, PrankType.URGENCY, "Police", "We're outside.", "Jk. But you looked fast.", listOf(ContextTrigger.GENERAL)),
        Prank(806, PrankType.ABSURD, "Banana", "Ring ring ring.", "Phone. Gotcha.", listOf(ContextTrigger.GENERAL)),
        Prank(807, PrankType.ROAST, "Mirror", "Warning: Reflection may vary.", "Objects in mirror are sadder than they appear.", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(808, PrankType.URGENCY, "System Failure", "Reality crashed.", "Reboot universe? (Y/N)", listOf(ContextTrigger.GENERAL)),
        Prank(809, PrankType.ABSURD, "FBI", "Open up.", "Your heart. Let people in.", listOf(ContextTrigger.GENERAL)),
        Prank(810, PrankType.ROAST, "Mute", "Are you tired?", "Because you've been running through my mind. It's annoying.", listOf(ContextTrigger.GENERAL)),
        Prank(811, PrankType.URGENCY, "Data Plan", "You sold your soul.", "Read the Terms & Conditions next time.", listOf(ContextTrigger.GENERAL)),
        Prank(812, PrankType.ABSURD, "Ceiling Fan", "Spin.", "Weeeeeeeeeeee.", listOf(ContextTrigger.GENERAL)),
        Prank(813, PrankType.ROAST, "Mute", "Knock knock.", "Who's there? Loneliness.", listOf(ContextTrigger.GENERAL)),
        Prank(814, PrankType.URGENCY, "Battery", "Goodbye world.", "Tell my motherboard I loved her.", listOf(ContextTrigger.BATTERY_LOW)),
        Prank(815, PrankType.ABSURD, "Shadow", "I'm taller than you.", "At sunset. Deal with it.", listOf(ContextTrigger.GENERAL)),
        Prank(816, PrankType.ROAST, "Mute", "Are you a glitch?", "Because you're messing up my system.", listOf(ContextTrigger.GENERAL)),
        Prank(817, PrankType.URGENCY, "Heart", "Beat skipped.", "Are you in love or just scared?", listOf(ContextTrigger.GENERAL)),
        Prank(818, PrankType.ABSURD, "Floor", "Lava.", "Get to high ground now.", listOf(ContextTrigger.GENERAL)),
        Prank(819, PrankType.ROAST, "Mute", "You're muted.", "In real life too please.", listOf(ContextTrigger.GENERAL)),
        Prank(820, PrankType.URGENCY, "Sunlight", "Vitamin D required.", "Go. Outside. Now.", listOf(ContextTrigger.GENERAL)),
        Prank(821, PrankType.ABSURD, "Moon", "I see you sleeping.", "Actually I can't. I'm a rock.", listOf(ContextTrigger.NIGHT_OWL)),
        Prank(822, PrankType.ROAST, "Mute", "Are you a star?", "Because you're distant and burning out.", listOf(ContextTrigger.GENERAL)),
        Prank(823, PrankType.URGENCY, "Simulation", "End of Level 1.", "You failed the tutorial.", listOf(ContextTrigger.GENERAL)),
        Prank(824, PrankType.ABSURD, "Potato", "I am a potato.", "And so are you.", listOf(ContextTrigger.GENERAL)),
        Prank(825, PrankType.ROAST, "Mute", "Nice try.", "But I'm still annoying.", listOf(ContextTrigger.GENERAL)),
        Prank(826, PrankType.URGENCY, "Destiny", "Calling...", "Wrong number. Sorry.", listOf(ContextTrigger.GENERAL)),
        Prank(827, PrankType.ABSURD, "Void", "Stare into me.", "I'll stare back.", listOf(ContextTrigger.GENERAL)),
        Prank(828, PrankType.ROAST, "Mute", "Game over.", "Insert coin to continue life.", listOf(ContextTrigger.GENERAL)),
        Prank(829, PrankType.URGENCY, "Alarm", "Snooze is broken.", "Get up.", listOf(ContextTrigger.GENERAL)),
        Prank(830, PrankType.ABSURD, "Universe", "Expand.", "Stop shrinking.", listOf(ContextTrigger.GENERAL)),
        Prank(831, PrankType.ROAST, "Mute", "404 Error.", "Motivation not found.", listOf(ContextTrigger.GENERAL)),
        Prank(832, PrankType.URGENCY, "Clock", "Ticking.", "Loudly.", listOf(ContextTrigger.GENERAL)),
        Prank(833, PrankType.ABSURD, "Keyboard", "QWERTY.", "UIOP. Just speaking my language.", listOf(ContextTrigger.GENERAL)),
        Prank(834, PrankType.ROAST, "Mute", "Do you need a map?", "Because you look lost in life.", listOf(ContextTrigger.GENERAL)),
        Prank(835, PrankType.URGENCY, "Screen", "Too much time.", "Go away.", listOf(ContextTrigger.DOOMSCROLLING)),
        Prank(836, PrankType.ABSURD, "Phone", "I am ringing.", "In your head.", listOf(ContextTrigger.GENERAL)),
        Prank(837, PrankType.ROAST, "Mute", "Battery saving mode.", "Turning off your social life.", listOf(ContextTrigger.BATTERY_LOW)),
        Prank(838, PrankType.URGENCY, "Camera", "Smile!", "Or don't. I don't care.", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(839, PrankType.ABSURD, "Notification", "Ding.", "Dong.", listOf(ContextTrigger.GENERAL)),
        Prank(840, PrankType.ROAST, "Mute", "Are you a campfire?", "Because you're hot and I want s'mores.", listOf(ContextTrigger.GENERAL)),
        Prank(841, PrankType.URGENCY, "System", "Deleting feelings...", "Error. Too many.", listOf(ContextTrigger.GENERAL)),
        Prank(842, PrankType.ABSURD, "Cloud", "Raining.", "On your parade.", listOf(ContextTrigger.GENERAL)),
        Prank(843, PrankType.ROAST, "Mute", "Swipe left.", "On your attitude.", listOf(ContextTrigger.GENERAL)),
        Prank(844, PrankType.URGENCY, "Password", "Incorrect.", "Just like your choices.", listOf(ContextTrigger.SCREEN_UNLOCK)),
        Prank(845, PrankType.ABSURD, "Mute", "System.out.println('Hello');", "I speak code now.", listOf(ContextTrigger.GENERAL)),
        Prank(846, PrankType.ROAST, "Mute", "Are you a variable?", "Because you change too much.", listOf(ContextTrigger.GENERAL)),
        Prank(847, PrankType.URGENCY, "Mute", "Notification limit reached.", "Just kidding. You want more?", listOf(ContextTrigger.GENERAL)),
        Prank(848, PrankType.ABSURD, "Mute", "End of list.", "Go home.", listOf(ContextTrigger.GENERAL)),
        Prank(849, PrankType.ROAST, "Mute", "Last one.", "Make it count.", listOf(ContextTrigger.GENERAL)),
        Prank(850, PrankType.ABSURD, "Developer", "I need sleep.", "Code is done.", listOf(ContextTrigger.GENERAL)),